### ISSUE TITLE
URL capitals issue

### ISSUE THREAD

**Issue by thechantaro** [Mavulp/hivefriends#99]
As I commented and clicked on my profile today, I was redirected to URL: https://friends.hivecom.net/Chantaro
However since my URL is actually chantaro with a lowercase letter is reports this as a non existent user.
It only brings this up when I click on my profile on a comment. Similar issue to the one that qwer.ee had?

**Comment by dolanske** [comment]
When I create a comment I do not send the author. The author field is set by the backend and it most have some confusion between `username `/ `displayName `because in some cases it returns the `displayName `instead.

I tested changing my own name to a different `displayName` and tested around the site, with comments, tags and links and nothing broke for me.

**Comment by dolanske** [comment]
Taggin @fkaa since he implemented the comments ( I think )

**Comment by dolanske** [comment]
This will be fixed with migrations. The bug happens when user logs in with capitalized letters in their name

**Comment by Jokler** [comment]
Reopening since it is not fixed yet.
